### PR TITLE
reduce gem size / remove unused tasks + dependency

### PR DESCRIPTION
**Pull request by grosser**
@splattael

### CODE REVIEW

**Comment by splattael** [comment]
@grosser Thanks :+1: 

Should we get rid of codeclimate completely or just update?

**Comment by grosser** [comment]
removed it completely same with docs links that go into nowhere and have no info :)

**Comment by grosser** [comment]
FYI https://github.com/grosser/single_cov if you care about code-coverage

**Comment by splattael** [comment]
LGTM :+1: :purple_heart:

**Pull request merged**
